<Project Sdk="Microsoft.NET.Sdk.Worker">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>dotnet-IngestionService-d35f14ca-258f-442e-b847-0b22bd1aa5a6</UserSecretsId>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="..\ChatBuddy.ServiceDefaults\ChatBuddy.ServiceDefaults.csproj" />
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.3"/>
    </ItemGroup>
    <ItemGroup>
      <None Update="incident_dataset\incident-01.md">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="incident_dataset\incident-02.md">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="incident_dataset\incident-03.md">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="incident_dataset\incident-04.md">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="incident_dataset\incident-05.md">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="incident_dataset\incident-06.md">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="incident_dataset\incident-07.md">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="incident_dataset\incident-08.md">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="incident_dataset\incident-09.md">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="incident_dataset\incident-10.md">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="incident_dataset\incident-11.md">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="incident_dataset\incident-12.md">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="incident_dataset\incident-13.md">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="incident_dataset\incident-14.md">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="incident_dataset\incident-15.md">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="incident_dataset\incident-16.md">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="incident_dataset\incident-17.md">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="incident_dataset\incident-18.md">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="incident_dataset\incident-19.md">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="incident_dataset\incident-20.md">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="incident_dataset\incident-21.md">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="incident_dataset\incident-22.md">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="incident_dataset\incident-23.md">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="incident_dataset\incident-24.md">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="incident_dataset\incident-25.md">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
    </ItemGroup>
</Project>
